---
# file: roles/common/tasks/nagios.yml

- name: Create directory if it doesn't exist
  file:
    path: /etc/systemd/system/nagios-nrpe-server.service.d
    state: directory
  tags: nagios

- name: synchronize nagios configuration files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  tags: nagios
  with_items:
    - { src: 'files/etc/nagios/nrpe.cfg', dest: '/etc/nagios/nrpe.cfg', owner: 'root', group: 'nagios', mode: '0640' }
    - { src: 'files/etc/systemd/system/nagios-nrpe-server.service.d/override.conf', dest: '/etc/systemd/system/nagios-nrpe-server.service.d/override.conf', owner: 'root', group: 'root', mode: '0644' }
  register: sync_result

- name: be sure nagios is running and enabled
  service:
    name: nagios-nrpe-server
    state: restarted
    enabled: yes
  tags: nagios
  when: sync_result.changed
