---
# file: roles/common/tasks/postfix.yml

- name: be sure postfix is installed
  apt:
    name: postfix
    state: present
  tags: postfix

- name: copy postfix configuration file
  template:
    src: postfix_main.j2
    dest: /etc/postfix/main.cf
  register: sync_result
  tags: postfix

- name: be sure postfix is running and enabled
  service:
    name: postfix
    state: restarted
    enabled: yes
  tags: postfix
  when: sync_result.changed
