---
# file: roles/common/tasks/ps1.yml

- name: custom ps1
  lineinfile:
    path: /root/.bashrc
    regexp: '^PS1'
    line: "PS1='\\[\\033]0;\\u@\\h:\\w\\007\\]\\[\\033[01;31m\\]\\h:\\[\\033[01;34m\\]\\w\\$\\[\\033[00m\\] '"
  tags: ps1
