---
# file: roles/common/tasks/sysctl.yml

- name: Set sysctl settings
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop:
    - { name: "net.core.wmem_max", value: "262144" }
    - { name: "net.core.rmem_max", value: "262144" }
    - { name: "net.ipv4.tcp_wmem", value: "4096 131072 4194304" }
    - { name: "net.ipv4.tcp_rmem", value: "4096 131072 6291456" }
    - { name: "net.core.somaxconn", value: "32768" }
    - { name: "net.core.netdev_max_backlog", value: "4096" }
    - { name: "net.ipv4.ip_local_port_range", value: "10000 65535" }
    - { name: "net.ipv4.tcp_tw_reuse", value: "1" }
    - { name: "net.ipv4.tcp_syncookies", value: "1" }
    - { name: "net.ipv4.tcp_max_syn_backlog", value: "262144" }
    - { name: "net.ipv4.tcp_fin_timeout", value: "15" }
    - { name: "net.ipv4.tcp_keepalive_time", value: "3600" }
    - { name: "net.ipv4.tcp_keepalive_intvl", value: "45" }
    - { name: "net.ipv4.tcp_max_orphans", value: "262144" }
    - { name: "vm.overcommit_memory", value: "1" }
  tags: sysctl
